# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Architecto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Architecto

  target 'ArchitectoTests' do
    inherit! :search_paths
	pod 'KBImageView'
    # Pods for testing
  end

  target 'ArchitectoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
